# Template for standard CI/CD process for HCA projects

services:
  - name: quay.io/ebi-ait/ingest-base-images:docker-dind
    alias: docker

# Override these variables in project .gitlab-ci.yaml as required
variables:
  APP_NAME: $CI_PROJECT_NAME
  DEV_REPLICAS: 1
  STAGING_REPLICAS: 1
  PROD_REPLICAS: 1
  IMAGE_NAME: quay.io/ebi-ait/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  DEV_RELEASE_IMAGE: quay.io/ebi-ait/$CI_PROJECT_NAME:latest-dev
  MASTER_RELEASE_IMAGE: quay.io/ebi-ait/$CI_PROJECT_NAME:latest
  # Repository that contains share YAMLs that are used across all ingest components. E.g. dev.yaml, staging.yaml and prod.yaml
  SHARED_CONFIG_REPO: https://github.com/ebi-ait/ingest-kube-deployment.git
  SHARED_CONFIG_DIR: apps

# Override these variables in project .gitlab-ci.yaml as required
# If another stage is added to project .gitlab-ci.yaml, all stages will need to be specified in project .gitlab-ci.yaml
# For example, you may want to add a unit-test stage
stages:
  - build
  - release
  - deploy
  - integration

Build:
  stage: build
  tags:
    - dind
  script:
    - echo $QUAY_PASSWORD | docker login quay.io -u $QUAY_USERNAME --password-stdin
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

Release dev:
  stage: release
  only:
    - dev
  tags:
    - dind
  script:
    - echo $QUAY_PASSWORD | docker login quay.io -u $QUAY_USERNAME --password-stdin
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $DEV_RELEASE_IMAGE
    - docker push $DEV_RELEASE_IMAGE

Release master:
  stage: release
  only:
    - master
  tags:
    - dind
  script:
    - echo $QUAY_PASSWORD | docker login quay.io -u $QUAY_USERNAME --password-stdin
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $MASTER_RELEASE_IMAGE
    - docker push $MASTER_RELEASE_IMAGE

Deploy dev:
  stage: deploy
  only:
    - dev
  image: quay.io/ebi-ait/ingest-base-images:dtzar_helm-kubectl-3.5.0
  environment:
    name: dev
    url: https://dev.contribute.data.humancellatlas.org/
    kubernetes:
      namespace: dev-environment
  script:
    - git clone $SHARED_CONFIG_REPO shared_config
    - helm package k8s/$APP_NAME
    - helm upgrade -f shared_config/$SHARED_CONFIG_DIR/dev.yaml $APP_NAME k8s/$APP_NAME --set-string environment=dev,image=$DEV_RELEASE_IMAGE,replicas=$DEV_REPLICAS,gitlab_app=$CI_PROJECT_PATH_SLUG,gitlab_env=$CI_ENVIRONMENT_SLUG --wait --install

Integration dev:
  stage: integration
  needs: ["Deploy dev"]
  only:
    - dev
  trigger: 
    project: hca/ingest-integration-tests
    branch: dev
    strategy: depend

Deploy staging:
  stage: deploy
  only:
    - master
  image: quay.io/ebi-ait/ingest-base-images:dtzar_helm-kubectl-3.5.0
  environment:
    name: staging
    url: https://staging.contribute.data.humancellatlas.org/
    kubernetes:
      namespace: staging-environment
  script:
    - git clone $SHARED_CONFIG_REPO shared_config
    - helm package k8s/$APP_NAME
    - helm upgrade -f shared_config/$SHARED_CONFIG_DIR/staging.yaml $APP_NAME k8s/$APP_NAME --set-string environment=staging,image=$MASTER_RELEASE_IMAGE,replicas=$STAGING_REPLICAS,gitlab_app=$CI_PROJECT_PATH_SLUG,gitlab_env=$CI_ENVIRONMENT_SLUG --wait --install

Integration staging:
  stage: integration
  needs: ["Deploy staging"]
  only:
    - master
  trigger:
    project: hca/ingest-integration-tests
    branch: staging
    strategy: depend

Deploy prod:
  stage: deploy
  only:
    - master
  when: manual
  allow_failure: false
  image: quay.io/ebi-ait/ingest-base-images:dtzar_helm-kubectl-3.5.0
  environment:
    name: prod
    url: https://contribute.data.humancellatlas.org/
    kubernetes:
      namespace: prod-environment
  script:
    - git clone $SHARED_CONFIG_REPO shared_config
    - helm package k8s/$APP_NAME
    - helm upgrade -f shared_config/$SHARED_CONFIG_DIR/prod.yaml $APP_NAME k8s/$APP_NAME --set-string environment=prod,image=$MASTER_RELEASE_IMAGE,replicas=$PROD_REPLICAS,gitlab_app=$CI_PROJECT_PATH_SLUG,gitlab_env=$CI_ENVIRONMENT_SLUG --wait --install

Integration prod:
  stage: integration
  needs: ["Deploy prod"]
  only:
    - master
  trigger:
    project: hca/ingest-integration-tests
    branch: prod
    strategy: depend
